import test from 'node:test'; import assert from 'node:assert/strict';
import { GiftService } from '../src/application/gift-service.js'; import { JsonStore, MemoryStorage } from '../src/infrastructure/local-store.js';
const make=()=>new GiftService(new JsonStore(new MemoryStorage()),()=>1700000000000);const complete={type:'gift',giftId:'99',giftName:'Completo',diamondCount:10,icon:'https://cdn.test/g.png',count:2};
test('descobre e deduplica pelo ID',()=>{const s=make();s.observe(complete);s.observe({...complete,count:3});assert.equal(s.discoveries.length,1);assert.equal(s.discoveries[0].seen,5)});
test('salvar não cataloga',()=>{const s=make();s.observe(complete);s.save('99');assert.equal(s.saved.length,1);assert.equal(s.verified.length,0);assert.equal(s.discoveries.length,1)});
test('incompleto pode salvar mas não catalogar',()=>{const s=make();s.observe({type:'gift',giftId:'7',giftName:'Sem foto',diamondCount:0});s.save('7');assert.throws(()=>s.verify('7'),/falta value, image/);assert.equal(s.saved.length,1);assert.equal(s.verified.length,0)});
test('editar permite catalogar depois',()=>{const s=make();s.observe({type:'gift',giftId:'7',giftName:'Revisar'});s.save('7');s.edit('7',{diamondCount:5,icon:'https://cdn.test/7.png'});s.verify('7');assert.equal(s.verified.length,1);assert.equal(s.discoveries.length,0);assert.equal(s.saved.length,1)});
test('limpar histórico preserva salvos e verificados',()=>{const s=make();s.observe(complete);s.save('99');s.verify('99');s.observe({...complete,giftId:'100',giftName:'Outro'});assert.equal(s.discoveries.length,1);s.clearHistory();assert.equal(s.discoveries.length,0);assert.equal(s.saved.length,1);assert.equal(s.verified.length,1)});
test('ID já verificado não volta a descobertos',()=>{const s=make();s.seedVerified({schema:'liveplus.verified-gifts.v1',gifts:[{id:'99',name:'Completo',diamondCount:10,icon:'https://cdn.test/g.png'}]});assert.equal(s.observe(complete).kind,'known');assert.equal(s.discoveries.length,0)});
