import { GiftService } from '../application/gift-service.js';
import { JsonStore } from '../infrastructure/local-store.js';
import { GameLiveSource } from '../infrastructure/game-live-source.js';
import { catalogValidation } from '../domain/gift.js';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store=new JsonStore(localStorage),service=new GiftService(store),source=new GameLiveSource();let tab='discoveries',active=false;
async function seed(force=false){if(!force&&service.verified.length)return;const payload=await fetch('./data/verified-gifts.json').then(r=>r.json());service.seedVerified(payload);render()}
function setStatus(text,ok=false){const e=$('#status');e.textContent=text;e.style.color=ok?'#86efac':''}
function render(){['discoveries','saved','verified'].forEach(k=>$('#n-'+k).textContent=service[k].length);const q=$('#search').value.trim().toLowerCase();const list=service[tab].filter(g=>`${g.name} ${g.id}`.toLowerCase().includes(q));$('#list').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Nenhum presente nesta lista.</div>'}
function card(g){const check=catalogValidation(g),missing=check.missing.map(x=>`FALTA ${x.toUpperCase()}`),img=g.icon?`<img src="${esc(g.icon)}" alt="">`:'<div class="placeholder">SEM<br>IMAGEM</div>';let actions='';if(tab==='discoveries')actions=`<button data-act="edit" data-id="${esc(g.id)}">EDITAR</button><button data-act="save" data-id="${esc(g.id)}">SALVAR</button><button class="catalog" data-act="verify" data-id="${esc(g.id)}" ${check.ok?'':'disabled'}>+ CATÁLOGO</button>`;if(tab==='saved')actions=`<button data-act="edit" data-id="${esc(g.id)}">EDITAR</button><button class="catalog" data-act="verify" data-id="${esc(g.id)}" ${check.ok?'':'disabled'}>+ CATÁLOGO</button><button data-act="remove" data-id="${esc(g.id)}">REMOVER</button>`;return `<article class="gift">${img}<div><h3>${esc(g.name)}</h3><div class="meta">ID ${esc(g.id)} · ${g.diamondCount>0?`${g.diamondCount} 💎`:'VALOR NÃO IDENTIFICADO'}</div><div class="badges">${missing.map(x=>`<span class="badge warn">${x}</span>`).join('')}<span class="badge">${g.seen||g.liveVerifiedCount||1}× observado</span></div><div class="actions">${actions}</div></div></article>`}
$('#toggle').addEventListener('click',()=>{if(active){source.disconnect();active=false;$('#toggle').textContent='INICIAR OBSERVAÇÃO';setStatus('OBSERVADOR OFF');return}try{source.connect({username:$('#username').value,key:$('#key').value,onGift:d=>{service.observe(d);render()},onStatus:s=>{if(s==='connected')setStatus(`OBSERVANDO @${$('#username').value.replace(/^@/,'')}`,true);else setStatus(String(s).toUpperCase())},onError:e=>setStatus('FALHA · '+e.message)});active=true;$('#toggle').textContent='PARAR OBSERVAÇÃO';setStatus('CONECTANDO...')}catch(e){setStatus('FALHA · '+e.message)}});
$('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').addEventListener('input',render);
$('#clear').addEventListener('click',()=>{if(confirm('Limpar somente o histórico de DESCOBERTOS? Salvos e Verificados serão mantidos.')){service.clearHistory();render();setStatus('HISTÓRICO LIMPO · SALVOS E VERIFICADOS MANTIDOS',true)}});$('#import').addEventListener('click',()=>seed(true));
$('#list').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const id=b.dataset.id;try{if(b.dataset.act==='save')service.save(id);if(b.dataset.act==='remove')service.removeSaved(id);if(b.dataset.act==='verify')service.verify(id);if(b.dataset.act==='edit'){const g=service.discoveries.find(x=>x.id===id)||service.saved.find(x=>x.id===id),value=prompt('Valor em moedas/diamantes:',g?.diamondCount||'');if(value!==null){const n=Number(String(value).replace(',','.'));if(!Number.isFinite(n)||n<=0)throw new Error('Valor inválido.');const icon=g?.icon||prompt('URL da imagem:','')||'';service.edit(id,{diamondCount:n,icon})}}render()}catch(err){alert(err.message)}});
seed().then(render).catch(e=>setStatus('CATÁLOGO BASE: '+e.message));window.__giftLab={service,source,render};
