import { GiftService } from '../application/gift-service.js';
import { JsonStore } from '../infrastructure/local-store.js';
import { GameLiveSource } from '../infrastructure/game-live-source.js';
import { catalogValidation } from '../domain/gift.js';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store=new JsonStore(localStorage),service=new GiftService(store),source=new GameLiveSource();let tab='discoveries',active=false,healthTimer=null;
const health={user:'',bridge:false,bridgeReady:false,tiktok:false,offline:false,connectedAt:0,lastEventAt:0,lastEventType:'',lastGift:'',eventCount:0,giftCount:0,mode:'—',reconnects:0,reason:'—',heartbeatAt:0,lastPacketAt:0};
async function seed(force=false){if(!force&&service.verified.length)return;const payload=await fetch('./data/verified-gifts.json').then(r=>r.json());service.seedVerified(payload);render()}
function setStatus(text,ok=false){const e=$('#status');e.textContent=text;e.title=text;e.style.color=ok?'#86efac':''}
function setActive(value){active=value;$('#toggle').textContent=value?'PARAR OBSERVAÇÃO':'INICIAR OBSERVAÇÃO'}
function fmtDuration(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60,h=Math.floor(m/60);return h?`${String(h).padStart(2,'0')}:${String(m%60).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function eventLabel(k=''){return({gift:'PRESENTE',like:'CURTIDA',chat:'CHAT',follow:'FOLLOW',share:'SHARE'})[k]||String(k||'EVENTO').toUpperCase()}
function setHealthField(id,value,kind='',hint){const b=$('#'+id),h=$('#'+id+'-hint');if(b){b.textContent=value;b.className=kind}if(h&&hint!==undefined)h.textContent=hint}
function renderHealth(){const now=Date.now(),age=health.lastEventAt?now-health.lastEventAt:null;setHealthField('h-user',health.user?`@${health.user}`:'—','',health.user?'Conta solicitada ao Connector':'Informe o @ acima');setHealthField('h-bridge',health.bridgeReady?'OK':health.bridge?'CONECTANDO':'OFF',health.bridgeReady?'ok':health.bridge?'warn':'err',health.bridgeReady?'WebSocket/Connector respondeu READY':health.bridge?'WebSocket aberto; aguardando READY':'WebSocket não conectado');
 if(health.tiktok)setHealthField('h-live','CONECTADA','ok','Sessão confirmada pelo status connected do TikTok');else if(health.offline)setHealthField('h-live','OFFLINE','warn','TikTok informou que esta Live está offline');else if(active&&health.bridgeReady)setHealthField('h-live','LOCALIZANDO','warn','Connector ativo; aguardando confirmação da Live');else setHealthField('h-live','OFF','err','Nenhuma sessão TikTok confirmada');
 let ev='AGUARDANDO',evKind='',evHint='Nenhum evento recebido';if(health.tiktok&&age===null){ev='CANAL ATIVO';evKind='ok';evHint='Live conectada; aguardando primeira interação'}else if(health.tiktok&&age<70000){ev='RECEBENDO';evKind='ok';evHint=`${eventLabel(health.lastEventType)} recebido há ${Math.round(age/1000)}s`}else if(health.tiktok&&age<115000){ev='SEM INTERAÇÃO';evKind='warn';evHint=`Último evento há ${Math.round(age/1000)}s; conexão continua ativa`}else if(health.tiktok&&age!==null){ev='LIVE QUIETA';evKind='warn';evHint=`Sem eventos há ${Math.round(age/1000)}s; silêncio não significa queda`}else if(health.offline){ev='OFFLINE';evKind='warn';evHint='Não há Live ativa para receber eventos'}setHealthField('h-events',ev,evKind,evHint);
 setHealthField('h-gifts',String(health.giftCount),health.giftCount?'ok':'',`${health.giftCount} evento${health.giftCount===1?'':'s'} gift nesta sessão`);setHealthField('h-last',health.lastEventAt?`${eventLabel(health.lastEventType)} · ${new Date(health.lastEventAt).toLocaleTimeString('pt-BR')}`:'—',health.lastEventAt?'ok':'',health.lastGift&&health.lastEventType==='gift'?health.lastGift:'Nenhum pacote da Live');setHealthField('h-time',health.tiktok&&health.connectedAt?fmtDuration(now-health.connectedAt):'00:00');setHealthField('h-mode',health.mode||'—');setHealthField('h-reconnects',String(health.reconnects),health.reconnects?'warn':'');setHealthField('h-reason',health.reason||'—',health.reason&&health.reason!=='—'?'warn':'',health.reason&&health.reason!=='—'?'Última causa informada pelo Connector':'Sem falhas registradas');
 const badge=$('#healthBadge');if(badge){let label='AGUARDANDO',cls='off';if(health.tiktok){label='LIVE OK';cls='on'}else if(health.offline){label='LIVE OFFLINE';cls='warn'}else if(active&&health.bridgeReady){label='LOCALIZANDO';cls='warn'}else if(active){label='CONECTANDO';cls='warn'}badge.className='healthBadge '+cls;badge.innerHTML=`<i></i> ${label}`}
 const line=$('#activityLine');if(line){if(health.tiktok&&health.lastEventAt)line.textContent=`Recebimento confirmado: ${eventLabel(health.lastEventType)} há ${Math.round(age/1000)}s · ${health.eventCount} interações · ${health.giftCount} presentes.`;else if(health.tiktok)line.textContent='Live conectada. Canal aberto e aguardando a primeira interação.';else if(health.offline)line.textContent='Conta localizada, porém o TikTok informou que a Live está offline.';else if(active&&health.bridgeReady)line.textContent='Connector respondeu. Procurando a sala TikTok e aguardando confirmação.';else if(active)line.textContent='Abrindo canal com o Connector...';else line.textContent='Aguardando conexão com o Connector.'}}
function resetHealth(user=''){Object.assign(health,{user:String(user||'').replace(/^@/,'').trim(),bridge:false,bridgeReady:false,tiktok:false,offline:false,connectedAt:0,lastEventAt:0,lastEventType:'',lastGift:'',eventCount:0,giftCount:0,mode:'—',reconnects:0,reason:'—',heartbeatAt:0,lastPacketAt:0});renderHealth()}
function render(){['discoveries','saved','verified'].forEach(k=>$('#n-'+k).textContent=service[k].length);const q=$('#search').value.trim().toLowerCase();const list=service[tab].filter(g=>`${g.name} ${g.id}`.toLowerCase().includes(q));$('#list').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Nenhum presente nesta lista.</div>'}
function card(g){const check=catalogValidation(g),missing=check.missing.map(x=>`FALTA ${x.toUpperCase()}`),img=g.icon?`<img src="${esc(g.icon)}" alt="">`:'<div class="placeholder">SEM<br>IMAGEM</div>';let actions='';if(tab==='discoveries')actions=`<button data-act="edit" data-id="${esc(g.id)}">EDITAR</button><button data-act="save" data-id="${esc(g.id)}">SALVAR</button><button class="catalog" data-act="verify" data-id="${esc(g.id)}" ${check.ok?'':'disabled'}>+ CATÁLOGO</button>`;if(tab==='saved')actions=`<button data-act="edit" data-id="${esc(g.id)}">EDITAR</button><button class="catalog" data-act="verify" data-id="${esc(g.id)}" ${check.ok?'':'disabled'}>+ CATÁLOGO</button><button data-act="remove" data-id="${esc(g.id)}">REMOVER</button>`;return `<article class="gift">${img}<div><h3>${esc(g.name)}</h3><div class="meta">ID ${esc(g.id)} · ${g.diamondCount>0?`${g.diamondCount} 💎`:'VALOR NÃO IDENTIFICADO'}</div><div class="badges">${missing.map(x=>`<span class="badge warn">${x}</span>`).join('')}<span class="badge">${g.seen||g.liveVerifiedCount||1}× observado</span></div><div class="actions">${actions}</div></div></article>`}
function statusFromLive(s,d={}){health.lastPacketAt=Date.now();if(d.mode)health.mode=d.mode;if(d.reason)health.reason=String(d.reason);if(s==='bridge'){health.bridge=true;setStatus('CONECTANDO AO CONNECTOR')}else if(s==='bridge-ready'){health.bridge=true;health.bridgeReady=true;setStatus('CONNECTOR OK · LOCALIZANDO LIVE')}else if(s==='connected'){health.bridge=true;health.bridgeReady=true;health.tiktok=true;health.offline=false;health.connectedAt=Date.now();health.reason='—';setActive(true);setStatus(`LIVE CONECTADA · @${d.username||health.user}`,true)}else if(s==='checking'){setStatus(`PROCURANDO @${d.username||health.user}`)}else if(s==='reconnecting'){health.tiktok=false;health.reconnects++;setStatus(`RECONECTANDO${d.attempt?' · '+d.attempt:''}`)}else if(s==='offline'){health.tiktok=false;health.offline=true;health.reason=d.reason||'TikTok informou Live offline';setActive(false);setStatus(`LIVE OFFLINE · @${d.username||health.user}`)}else if(s==='zombie'){health.tiktok=false;health.reason=d.reason||'Sessão sem resposta';setStatus('LIVE SEM RESPOSTA')}else if(s==='heartbeat'){health.heartbeatAt=Date.now();if(d.mode)health.mode=d.mode}else if(s==='authenticating'){setStatus('VALIDANDO CONNECTOR')}else if(s==='error'){health.tiktok=false;health.reason=d.reason||'Erro ao conectar';setActive(false);setStatus('FALHA AO CONECTAR')}else if(s==='disconnected'){health.tiktok=false;if(d.reason==='websocket'){health.bridge=false;health.bridgeReady=false;setActive(false);setStatus('CONNECTOR DESCONECTADO')}else setStatus('LIVE DESCONECTADA')}renderHealth()}
function activityFromLive(type,d={}){health.tiktok=true;health.offline=false;health.lastEventAt=Date.now();health.lastEventType=type;health.eventCount++;if(d.mode)health.mode=d.mode;if(type==='gift'){health.giftCount++;health.lastGift=`${d.gift||d.giftName||'Presente'} · ID ${d.giftId??'—'} · ${Number(d.diamondCount)||0} 💎`;service.observe(d);render()}setStatus(`RECEBENDO · ${eventLabel(type)}${type==='gift'&&d.gift?' · '+d.gift:''}`,true);renderHealth()}
$('#toggle').addEventListener('click',()=>{if(active){source.disconnect();setActive(false);resetHealth($('#username').value);setStatus('OBSERVADOR OFF');return}try{const user=$('#username').value.trim();resetHealth(user);setActive(true);source.connect({username:user,onGift:()=>{},onActivity:activityFromLive,onPacket:()=>{health.lastPacketAt=Date.now()},onStatus:statusFromLive,onError:e=>{health.reason=e.message;health.tiktok=false;setActive(false);setStatus('FALHA NO OBSERVADOR');renderHealth();source.disconnect()}});setStatus('CONECTANDO AO CONNECTOR')}catch(e){setActive(false);health.reason=e.message;setStatus('FALHA NO OBSERVADOR');renderHealth()}});
$('#username').addEventListener('keydown',e=>{if(e.key==='Enter'&&!active)$('#toggle').click()});
$('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#search').addEventListener('input',render);
$('#clear').addEventListener('click',()=>{if(confirm('Limpar somente o histórico de DESCOBERTOS? Salvos e Verificados serão mantidos.')){service.clearHistory();render();setStatus('HISTÓRICO LIMPO',true)}});$('#import').addEventListener('click',()=>seed(true));
$('#list').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const id=b.dataset.id;try{if(b.dataset.act==='save')service.save(id);if(b.dataset.act==='remove')service.removeSaved(id);if(b.dataset.act==='verify')service.verify(id);if(b.dataset.act==='edit'){const g=service.discoveries.find(x=>x.id===id)||service.saved.find(x=>x.id===id),value=prompt('Valor em moedas/diamantes:',g?.diamondCount||'');if(value!==null){const n=Number(String(value).replace(',','.'));if(!Number.isFinite(n)||n<=0)throw new Error('Valor inválido.');const icon=g?.icon||prompt('URL da imagem:','')||'';service.edit(id,{diamondCount:n,icon})}}render()}catch(err){alert(err.message)}});
healthTimer=setInterval(renderHealth,1000);window.addEventListener('beforeunload',()=>{clearInterval(healthTimer);source.disconnect()});seed().then(()=>{render();renderHealth()}).catch(e=>{health.reason=e.message;setStatus('ERRO NO CATÁLOGO BASE');renderHealth()});window.__giftLab={service,source,health,render,renderHealth};
